routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['namespace' => 'Admin'], function () {

    // why use name
    Route::get('admin/home', 'HomeController@index')->name('admin.name');

    // City route
    Route::resource('admin/city', 'CityController');

    // Country route
    Route::resource('admin/country', 'CountryController');

    // Place route
    Route::resource('admin/place', 'PlaceController');

    // Restaurant route
    Route::resource('admin/restaurant', 'RestaurantController');

    // Shop route
    Route::resource('admin/shop', 'ShopController');

    // Admin Route Login
    Route::get('admin-login', 'Auth\LoginController@showLoginForm')->name('admin.login');

    Route::post('admin-login','Auth\LoginController@login');

    // for drop down list depend on which country did client select
    Route::get('city/get/{id}', 'CityController@getCities');
    

});



Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', function (){

    return view('welcome');

});

app/Http/Controllers/Admin/CityController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\Admin\City;
use App\Model\Admin\Country;
use Illuminate\Support\Facades\DB;

class CityController extends Controller
{

    public function __construct()
    {
        return $this->middleware('auth:admin');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $cities = City::all();
        $countries = Country::all();
        return view('admin.city.index', compact('cities', 'countries'));

       // return City::all();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //

        $countries = Country::all();

        return view('admin.city.create', compact('countries'));


    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {



        //
        $this->validate($request, [

            'name' => 'required'

        ]);

            $city = new City;
            $city->name = $request->name;

            $country = new Country;
            $country->id = $request->country;

            $city->save();
            $city->country()->associate($country->id)->save();

            return redirect(route('city.index'));

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $city = City::where('id',$id)->first();
        $countries = Country::all();

        return view('admin.city.edit', compact('city', 'countries'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $this->validate($request, [

            'name' => 'required'

        ]);

        $city = City::find($id);

        $city->name = $request->name;

        $city->country_id = $request->country;

        $city->save();

        return redirect(route('city.index'));


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        City::where('id',$id)->delete();

        return redirect()->back();

    }

    // fetching all from cities table by passing country_id
    public function getCities($id)
    {
        $cities = DB::table("cities")->where('country_id', $id)->pluck('name', 'id');

        return json_encode($cities);
    }

}

resources/views/admin/city/create.blade.php
@extends('admin.layouts.app')



@section('main-content')

  <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Text Editors
                <small>Advanced form element</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="#">Forms</a></li>
                <li class="active">Editors</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-md-12">

                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Titles</h3>
                        </div>

                        @include('includes.messages')


                        <!-- /.box-header -->
                        <!-- form start -->
                        <form role="form" method="POST" action="{{ route('city.store') }}">

                            {{ csrf_field() }}

                            <div class="box-body">

                                <div class="col-lg-offset-3 col-lg-6">

                                    <div class="form-group">
                                        <label for="city">Enter City</label>
                                        <input type="text" class="form-control" id="name" name="name" placeholder="Enter City title">
                                    </div>

                                         <div class="form-group">
                                        <label>Select Country</label>
                                        <select name="country" class="form-control">
                                            <option disabled selected>Please choose country </option>
                                            @foreach($countries as $country)

                                            <option  value="{{  $country->id }}">{{ $country->name }}</option>

                                            @endforeach
                                        </select>
                                      </div>

                                    <div class="form-group">
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                        <a type="buttion" class="btn btn-warning" href="{{ route('city.index') }}">Back</a>
                                    </div>

                                </div>

                            </div>
                            <!-- /.box-body -->

                        </form>
                    </div>

                </div>
                <!-- /.col-->
            </div>
            <!-- ./row -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->


@endsection

resources/views/admin/city/edit.blade.php
@extends('admin.layouts.app')

@section('main-content')

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Text Editors
            <small>Advanced form element</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Forms</a></li>
            <li class="active">Editors</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-md-12">

                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Titles</h3>
                    </div>

                    @include('includes.messages')


                    <!-- /.box-header -->
                    <!-- form start -->
                    <form role="form" method="POST" action="{{ route('city.update', $city->id) }}">

                        {{ csrf_field() }}
                        {{ method_field('PATCH') }}

                        <div class="box-body">

                            <div class="col-lg-offset-3 col-lg-6">

                                <div class="form-group">
                                    <label for="city">Enter City</label>
                                    <input type="text" class="form-control" id="name" name="name" placeholder="Enter City title" value="{{ $city->name }}">
                                </div>

                                   <div class="form-group">
                                    <label>Select Country</label>
                                    <select class="form-control" name="country">
                                        <option selected disabled > Please Select country </option>
                                        @foreach($countries as $country)

                                      <option value="{{ $country->id }}">{{ $country->name }}</option>

                                        @endforeach
                                    </select>
                                  </div>

                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                    <a type="buttion" class="btn btn-warning" href="{{ route('city.index') }}">Back</a>
                                </div>

                            </div>

                        </div>
                        <!-- /.box-body -->

                    </form>
                </div>

            </div>
            <!-- /.col-->
        </div>
        <!-- ./row -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

@endsection

resources/views/admin/city/index.blade.php
@extends('admin.layouts.app')

@section('headSection')

 <link rel="stylesheet" href="{{ asset('admin/plugins/datatables/dataTables.bootstrap.css') }}">

@endsection

@section('main-content')

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Blank page
            <small>it all starts here</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Examples</a></li>
            <li class="active">Blank page</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Title</h3>
                    <a type="button" class="btn btn-success" href="{{ route('city.create') }}">Add City</a>
                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fa fa-minus"></i></button>
                    <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fa fa-times"></i></button>
                </div>
            </div>
            <div class="box-body">
                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>S.No</th>
                            <th>City </th>
                            <th>Country</th>
                            <th>Edit</th>
                            <th>Delete</th>
                        </tr>
                    </thead>



                    <tbody>
                        @foreach($cities as $city)
                        <tr>
                            <td>{{ $loop->index + 1 }}</td>
                            <td>{{ $city->name }}</td>
                            <td>
                                @foreach($countries as $country)
                                    @if($city->country_id == $country->id)
                                    {{ $country->name }}
                                    @endif
                                    @endforeach

                            </td>
                            <td> <a href="{{ route('city.edit', $city->id) }}"><span class="glyphicon glyphicon-edit"></span></a></td>
                            <td> <form action="{{ route('city.destroy', $city->id) }}" method="POST" id="delete-form-{{ $city->id }}">

                                {{ csrf_field() }}
                                {{ method_field('DELETE') }}
                            </form>
                            <a  onclick="
                                if(confirm('Are you sure you want to delete this ?')) {
                                    event.preventDefault();
                                    document.getElementById('delete-form-{{ $city->id }}').submit();
                                } else{
                                    event.preventDefault();
                                }

                            ">
                                <span class="glyphicon glyphicon-trash"></span>
                            </a>

                            </td>
                        </tr>
                        @endforeach
                    </tbody>

                    <th>S.No</th>
                    <th>City</th>
                    <th>Country</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </table>
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                Footer
            </div>
            <!-- /.box-footer-->
        </div>
        <!-- /.box -->

    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

@endsection

@section('footerSection')

<script src="{{ asset('admin/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('admin/plugins/datatables/dataTables.bootstrap.min.js') }}"></script>
<script>
    $(function () {
        $("#example1").DataTable();
        $('#example2').DataTable({
            "paging": true,
            "lengthChange": false,
            "searching": false,
            "ordering": true,
            "info": true,
            "autoWidth": false
        });
    });

</script>

@endsection