routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['namespace' => 'Admin'], function () {

    // why use name
    Route::get('admin/home', 'HomeController@index')->name('admin.name');

    // City route
    Route::resource('admin/city', 'CityController');

    // Country route
    Route::resource('admin/country', 'CountryController');

    // Place route
    Route::resource('admin/place', 'PlaceController');

    // Restaurant route
    Route::resource('admin/restaurant', 'RestaurantController');

    // Shop route
    Route::resource('admin/shop', 'ShopController');

    // Admin Route Login
    Route::get('admin-login', 'Auth\LoginController@showLoginForm')->name('admin.login');

    Route::post('admin-login','Auth\LoginController@login');

    // for drop down list depend on which country did client select
    Route::get('city/get/{id}', 'CityController@getCities');
    

});



Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', function (){

    return view('welcome');

});

app/Http/Controllers/Admin/ShopController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Model\Admin\City;
use App\Model\Admin\Country;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\Admin\Shop;

class ShopController extends Controller
{

    public function __construct()
    {
        return $this->middleware('auth:admin');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $shops = Shop::all();
        $countries = Country::all();
        $cities = City::all();
        return view('admin.shop.index',compact('shops', 'countries','cities'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $countries = Country::all();
        $cities    = City::all();
        return view('admin.shop.create',compact('countries','cities'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $this->validate($request, [

            'name' => 'required',
            'address' => 'required',
            'desc' => 'required',

        ]);

        if ($request->hasFile('image')){
            $shopImage = $request->image->store('public/images');
        } else {

            $shopImage = '';
        }

        $shop = new Shop;

        $shop->image        = $shopImage;
        $shop->name         = $request->name;
        $shop->address      = $request->address;
        $shop->desc         = $request->desc;
        $shop->mobile       = $request->mobile;
        $shop->country_id = $request->country;
        $shop->city_id    = $request->city;

        $shop->save();

        return redirect(route('shop.index'));


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $shop = Shop::where('id',$id)->first();
        $cities = City::all();
        $countries = Country::all();

        return view('admin.shop.edit', compact('shop','cities','countries'));


    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $this->validate($request,[

            'name' => 'required',
            'address' => 'required',
            'desc' => 'required',

        ]);


        $shop = Shop::find($id);


        $shop->name     = $request->name;
        $shop->address  = $request->address;
        $shop->desc     = $request->desc;
        $shop->mobile   = $request->mobile;
        $shop->country_id = $request->country;
        $shop->city_id    = $request->city;

        if ($request->hasFile('image')){
            $shopImage =  $request->image->store('public/images');
            $shop->image   = $shopImage;
           }


        $shop->save();

        return redirect(route('shop.index'));

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        Shop::where('id',$id)->delete();

        return redirect()->back();
    }
}

resources/views/admin/shop/create.blade.php
@extends('admin.layouts.app')

@section('main-content')


    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <section class="content-header">
          <h1>
              Shops
              <small>safreti</small>
          </h1>
          <ol class="breadcrumb">
              <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
              <li><a href="#">Forms</a></li>
              <li class="active">Editors</li>
          </ol>
      </section>

      <!-- Main content -->
      <section class="content">
          <div class="row">
              <div class="col-md-12">

                  <div class="box box-primary">
                      <div class="box-header with-border">
                          <h3 class="box-title">Titles</h3>
                      </div>


                      @include('includes.messages')



                      <!-- /.box-header -->
                      <!-- form start -->
                      <form role="form" method="POST" action="{{ route('shop.store') }}" enctype="multipart/form-data">
                          <div class="box-body">

                            {{ csrf_field() }}

                              <div class="col-lg-12">

                                  <div class="form-group">
                                      <label for="title">Shop Name </label>
                                      <input type="text" class="form-control" id="title" name="name" placeholder="Enter Shop">
                                  </div>


                                  <div class="form-group">
                                      <label for="sub title">Shop address</label>
                                      <input type="text" class="form-control" id="address" name="address" placeholder="Enter Address">
                                  </div>

                                  <div class="form-group">
                                      <label for="slug">Shop Description </label>
                                      <input type="text" class="form-control" id="desc" name="desc" placeholder="Enter Description">
                                  </div>

                                  <div class="form-group">
                                    <label for="slug">Shop Mobile </label>
                                    <input type="text" class="form-control" id="desc" name="mobile" placeholder="Enter Mobile">
                                </div>

                                <div class="form-group">
                                        <label>Select Country</label>
                                        <select name="country" class="form-control">
                                            <option value="">Please Select</option>
                                          @foreach($countries as $country)
                                            <option value="{{ $country->id }}"> {{ $country->name }}</option>
                                              @endforeach
                                        </select>
                                      </div>


                                  <div class="form-group">
                                      <label>Select City</label>
                                      <select name="city" class="form-control" id="city">
                                          <option>Please Select</option>
                                          <option>-- State -- </option>

                                      </select>
                                  </div>

                                  <div class="form-group">
                                    <label for="image">Shop Image</label>
                                    <input type="file" name="image" id="image">

                                    <p class="help-block">Example block-level help text here.</p>
                                </div>

                            <div class="form-group">
                              <button type="submit" class="btn btn-primary">Submit</button>
                              <a type="button" class="btn btn-warning" href="{{ route('shop.index') }}">Back</a>
                          </div>
                              </div>
                          </div>
                      </form>
                  </div>

              </div>
              <!-- /.col-->
          </div>
          <!-- ./row -->
      </section>
      <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

@endsection

@section('footerSection')
    <script type="text/javascript">


        $(document).ready(function () {
            $('select[name="country"]').on('change',function () {
                var countryId = $(this).val();
                if (countryId)
                {
                    $.ajax({
                        url: '/city/get/'+countryId,
                        type: "GET",
                        dataType: "json",
                        success: function (data) {

                            $('select[name="city"]').empty();
                            $.each(data, function (key, value) {
                                $('select[name="city"]').append('<option value="'+ key +'">' + value + '</option>');
                            });
                        }
                    });
                } else {
                    $('select[name="state"]').empty();
                }
            });
        });

    </script>
@endsection

resources/views/admin/shop/edit.blade.php
@extends('admin.layouts.app')

@section('main-content')

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
      <h1>
          Shops
          <small>safreti</small>
      </h1>
      <ol class="breadcrumb">
          <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
          <li><a href="#">Forms</a></li>
          <li class="active">Editors</li>
      </ol>
  </section>

  <!-- Main content -->
  <section class="content">
      <div class="row">
          <div class="col-md-12">

              <div class="box box-primary">
                  <div class="box-header with-border">
                      <h3 class="box-title">Titles</h3>
                  </div>


                  @include('includes.messages')



                  <!-- /.box-header -->
                  <!-- form start -->
                  <form role="form" method="POST" action="{{ route('shop.update', $shop->id) }}" enctype="multipart/form-data">
                      <div class="box-body">

                        {{ csrf_field() }}

                        {{ method_field('PATCH') }}

                          <div class="col-lg-12">

                              <div class="form-group">
                                  <label for="title">Shop Name </label>
                                  <input type="text" class="form-control" id="title" name="name" placeholder="Enter Shop" value="{{  $shop->name }}">
                              </div>


                              <div class="form-group">
                                  <label for="sub title">Shop address</label>
                                  <input type="text" class="form-control" id="address" name="address" placeholder="Enter Address" value="{{ $shop->address }}">
                              </div>

                              <div class="form-group">
                                  <label for="slug">Shop Description </label>
                                  <input type="text" class="form-control" id="desc" name="desc" placeholder="Enter Description" value="{{ $shop->desc }}">
                              </div>

                              <div class="form-group">
                                <label for="slug">Shop Mobile </label>
                                <input type="text" class="form-control" id="desc" name="mobile" placeholder="Enter Mobile" value="{{ $shop->mobile }}">
                            </div>

                            <div class="form-group">
                                    <label>Select Country</label>
                                    <select name="country" class="form-control">
                                            <option>Please Select</option>
                                        @foreach($countries as $country)
                                           <option value="{{ $country->id }}"

                                           @if($shop->country_id == $country->id)

                                             selected
                                                   @endif
                                           > {{$country->name}}
                                           </option>
                                            @endforeach
                                    </select>
                                  </div>


                                  <div class="form-group">
                                        <label>Select City</label>
                                        <select name="city" class="form-control">

                                            <option>Please Select</option>
                                            @foreach($cities as $city)
                                                <option value=" {{ $city->id }}"

                                                    @if($shop->city_id == $city->id)
                                                        selected
                                                        @endif
                                                    >{{ $city->name }}
                                                  </option>
                                                @endforeach
                                        </select>
                                      </div>

                              <div class="form-group">
                                <label for="image">Shop Image</label>
                                <input type="file" name="image" id="image">

                                <p class="help-block">Example block-level help text here.</p>
                                  <img class="img-responsive" width="100" height="100" src="{{ Storage::disk('local')->url($shop->image) }}" alt="">
                            </div>

                        <div class="form-group">
                          <button type="submit" class="btn btn-primary">Submit</button>
                          <a type="button" class="btn btn-warning" href="{{ route('shop.index') }}">Back</a>
                      </div>
                          </div>
                      </div>
                  </form>
              </div>

          </div>
          <!-- /.col-->
      </div>
      <!-- ./row -->
  </section>
  <!-- /.content -->
</div>
<!-- /.content-wrapper -->

@endsection

resources/views/admin/shop/index.blade.php
@extends('admin.layouts.app')

@section('headSection')

<link rel="stylesheet" href="{{ asset('admin/plugins/datatables/dataTables.bootstrap.css') }}">

@endsection

@section('main-content')

<div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Blank page
                <small>it all starts here</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="#">Examples</a></li>
                <li class="active">Blank page</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">

            <!-- Default box -->
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Title</h3>
                    <a type="buttion" class="btn btn-success" href="{{ route('shop.create') }}">Add Shop</a>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                            <i class="fa fa-minus"></i></button>
                        <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                            <i class="fa fa-times"></i></button>
                    </div>
                </div>
                <div class="box-body table-responsive">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>S.No</th>
                                <th>Name</th>
                                <th>Address</th>
                                <th>Description</th>
                                <th>Mobile</th>
                                <th>Image</th>
                                <th>Country</th>
                                <th>City</th>
                                <th>Edit</th>
                                <th>Delete</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($shops as $shop)
                            <tr>
                                <td>{{ $loop->index + 1 }}</td>
                                <td>{{ $shop->name }}</td>
                                <td>{{ $shop->address }}</td>
                                <td>{{ $shop->desc }}</td>
                                <td>{{ $shop->mobile }}</td>
                                <td><img class="img-responsive" height="100" width="100" src="{{ Storage::disk('local')->url($shop->image) }}" alt=""> </td>
                                <td>
                                    @foreach($countries as $country)
                                        @if($shop->country_id == $country->id)
                                        {{ $country->name }}
                                        @endif
                                     @endforeach

                                </td>
                                <td>
                                    @foreach($cities as $city)
                                        @if($shop->city_id == $city->id)
                                        {{ $city->name }}
                                        @endif

                                    @endforeach


                                </td>
                                <td><a href="{{ route('shop.edit', $shop->id) }}"><span class="glyphicon glyphicon-edit"></span></a></td>

                                <td>
                                    <form action="{{ route('shop.destroy', $shop->id) }}" id="form-delete-{{ $shop->id }}" method="POST">
                                        {{ csrf_field() }}
                                        {{ method_field('DELETE') }}
                                    </form>
                                    <a href="" onclick="
                                    if(confirm('Are you sure , you want to delete this ?')) {
                                        event.preventDefault();
                                        document.getElementById('form-delete-{{ $shop->id}}').submit();

                                    } else {
                                        event.preventDefault();
                                    }
                                    ">
                                    <span class="glyphicon glyphicon-trash"></span>
                                    </a>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                        <tfoot>
                                <tr>
                                    <th>S.No</th>
                                    <th>Name</th>
                                    <th>Address</th>
                                    <th>Description</th>
                                    <th>Mobile</th>
                                    <th>Image</th>
                                    <th>Country</th>
                                    <th>City</th>
                                    <th>Edit</th>
                                    <th>Delete</th>
                                </tr>
                            </tfoot>

                    </table>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    Footer
                </div>
                <!-- /.box-footer-->
            </div>
            <!-- /.box -->

        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->



@endsection

@section('footerSection')

<script src="{{ asset('admin/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('admin/plugins/datatables/dataTables.bootstrap.min.js') }}"></script>
<script>
     $(function () {
    $("#example1").DataTable();
    $('#example2').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false
    });
});
</script>


@endsection